function appReducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'TALKS_UPDATED': // ...
    case 'TALK_UPDATED': // ...
    case 'RATE': // ...
    case 'UNRATE': // ...
    case 'TALK_WATCHED': // ...

    default: return state;
  }
}
